- name: install redis server
  apt: name={{item}} state=present
  with_items:
    - redis-server
    - redis-tools

- name: set listen address
  lineinfile: >
    dest=/etc/redis/redis.conf
    regexp="^bind"
    line="bind {{ansible_all_ipv4_addresses[0]}}"
  notify:
    - restart redis

- name: set password
  lineinfile: >
    dest=/etc/redis/redis.conf
    line="requirepass {{WT_PASSWD}}"
  notify:
    - restart redis

- name: start redis service
  service: name=redis-server state=started enabled=yes
