- name: install redis server
  yum: name={{item}} state=present
  with_items:
    - redis

- name: configure firewalld
  firewalld: port=6379/tcp state=enabled permanent=true immediate=yes
  ignore_errors: true


- name: set listen address
  lineinfile: >
    dest=/etc/redis.conf
    regexp="^bind"
    line="bind {{ansible_all_ipv4_addresses[0]}}"
  notify:
    - restart redis

- name: set password
  lineinfile: >
    dest=/etc/redis.conf
    line="requirepass {{WT_PASSWD}}"
  notify:
    - restart redis

- name: start redis service
  service: name=redis state=started enabled=yes
