---
- hosts: all
  roles:
    - common

- hosts: postgres
  roles:
    - pgdatabase

- hosts: redis-cache
  roles:
    - redis

- hosts: es
  roles:
    - es

- hosts: wagtail-fe
  roles:
    - uwsgi
    - wagtail

- hosts: nginx
  roles:
    - nginx
  tags:
    - nginx
