- name: restart redis
  service: name=redis-server state=restarted enabled=yes
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int == 8

- name: restart redis
  service: name=redis state=restarted enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
