- name: install jdk1.7
  yum: name=java-1.7.0-openjdk.x86_64 state=latest

- name: copy es-1.7.5
  copy: src=files/elasticsearch-1.7.5.noarch.rpm dest=/tmp/elasticsearch-1.7.5.noarch.rpm

- name: install es 1.7.5
  yum: name="/tmp/elasticsearch-1.7.5.noarch.rpm" state=present

- name: configure firewalld
  firewalld: port={{item}}/tcp state=enabled permanent=true immediate=yes
  with_items:
    - 9200
    - 9300
  ignore_errors: true
