- name: enable external postgres repository
  lineinfile: >
    dest=/etc/apt/sources.list.d/postgres.list
    line="{{PG_REPOURL}}"
    create=yes
    owner=root
    group=root
    mode=0644

- name: import pgp_key for postgres repository
  apt_key: url={{PG_REPOKEY}}

- name: install postgresql database
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - postgresql-{{PG_VERSION}}
    - postgresql-client-{{PG_VERSION}}
    - python-psycopg2

- set_fact:
    PG_DATA: /var/lib/postgresql/9.5/main

- set_fact:
    PG_CONF: /etc/postgresql/9.5/main

- name: configure host base access
  template: >
    src=templates/pg_hba.conf.j2
    dest={{PG_CONF}}/pg_hba.conf
    owner=postgres
    group=postgres
    mode=0640

- name: configure postgresql server parameters
  template: >
    src=templates/postgresql.conf.j2
    dest={{PG_CONF}}/postgresql.conf
    owner=postgres
    group=postgres
    mode=0640
  notify:
    - restart postgresql-deb
    - create wagtail database
    - create wagtail user

- name: start postgresql
  service: name=postgresql state=started enabled=yes
