- name: restart postgresql
  service: name=postgresql state=restarted enabled=yes

- name: create wagtail database
  postgresql_db: name={{PROJ_NAME}}
  become: yes
  become_user: postgres
  environment:
    - PGUSER: postgres
    - PGHOST: /var/run/postgresql

- name: create wagtail user
  postgresql_user: >
    db="{{PROJ_NAME}}"
    name="{{WT_USER}}"
    password="{{WT_PASSWD}}"
    priv=CONNECT,ALL
  become: yes
  become_user: postgres
  environment:
    - PGUSER: postgres
    - PGHOST: /var/run/postgresql
